/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sm_myapplication_CameraActivity */

#ifndef _Included_com_sm_myapplication_CameraActivity
#define _Included_com_sm_myapplication_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sm_myapplication_CameraActivity_PERMISSIONS_REQUEST_CODE
#define com_sm_myapplication_CameraActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_sm_myapplication_CameraActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sm_myapplication_CameraActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
